### ISSUE TITLE
Snmp v1 support

### ISSUE THREAD

**Issue by giganteous** [mjibson/snmp#5]
Hi Matt,

I'd like snmp v1 support for a few alerts in our Bosun instance. I can write up a few extra lines of code to optionally alter the Version field.

Do you wan't to maintain that?

**Comment by mjibson** [comment]
I don't work on bosun anymore, so I'd prefer not to maintain this. I would actually prefer if this package is moved under the bosun or stackexchange namespace, since I don't use it for any of my own projects.

**Comment by giganteous** [comment]
Kyle said something in that trend: absorb it into bosun.

How do we proceed, do you transfer it to bosun-monitor? Or do you want @kylebrandt's approval?

thanks

**Comment by gbrayut** [comment]
I forked this to https://github.com/bosun-monitor/snmp so you can start to submit issues and PRs there.

**Comment by giganteous** [comment]
@gbrayut you need to enable issues for it.

I'm closing this, thanks!
